### ISSUE TITLE
Plugin have BUG on widget recent comments

### ISSUE THREAD

**Issue by dcrst75** [ultimatemember/ultimatemember#215]
Like I say on free support, plugin v1.3.78 have bug on Recent Comments widget.
For sure, I make an fresh install of WP 4.7 site without anything (plugin, themes, etc) at [http://www.donhome.net/wp](http://www.donhome.net/wp) and when I access page with comments  (Hello world), all comments from widget has changed to one user.
Please see up link
![30 12](https://cloud.githubusercontent.com/assets/24827370/21560650/eb6fcc02-ce6a-11e6-9b4c-89c6aafc0b25.png)

**Comment by champsupertramp** [comment]
@dcrst75 can you please try the pre-release version in the link?
https://github.com/ultimatemember/ultimatemember/releases

Let me know if you're still encountering issues. I tested with pre-release version and never encounter this issue.

**Comment by dcrst75** [comment]
Hi
Seems now working at first look. On test page at [https://www.donhome.net/wp](https://www.donhome.net/wp) not encounter this issue with pre-release 1.3.79.
If final version is the same, may close this ticket

**Comment by dcrst75** [comment]
Hi
I download from your link, but version is same 1.3.78 on archive **ultimatemember-pre-v1.3.79.8.zip** and the issue is still present

**Comment by champsupertramp** [comment]
Hi @dcrst75 Do you have UM extensions installed on your site when you test this issue?

**Comment by dcrst75** [comment]
No. Like I say on initial post, I have fresh WP 4.7 installed only with UM plugin at [https://www.donhome.net/wp](https://www.donhome.net/wp).
Strange....I dont touch this site ffrom days and....now working?!. Make more test for sure

**Comment by champsupertramp** [comment]
Hi,

I tested the latest pre-release version of Ultimate Member without extensions. I also use WP TwentyFifteen Theme and it works just fine on our end.

Here's the screenshot:
![um-widget-comments](https://cloud.githubusercontent.com/assets/12200688/21975050/6282d526-dc05-11e6-8503-e5c13cbf4551.png)




Regards,

**Comment by dcrst75** [comment]
I do not know what to think. My WP 4.7 site is fresh wihout anything on it. Can you provide me an email to give you admin access to this site? So you can test what I say

**Comment by champsupertramp** [comment]
Hi @dcrst75  can you please contact me at support@ultimatemember.com? Please do tell them that you're the guy from github repo. Thank you

**Comment by champsupertramp** [comment]
Hi @dcrst75,

I've fixed the issue. You can try the updated pre-release version in the link:
https://github.com/ultimatemember/ultimatemember/releases

Let me know if this resolves the issue on your end.

Regards,

**Comment by dcrst75** [comment]
Is not fixed. Seems only works with Twenty Fifteen default theme. But with Twenty Seventeen default theme or with Twenty Sixteen, issue still exist
